server:
  port: 80
  servlet:
    context-path: / #项目名称
spring:
  application:
    name: database
  datasource:
    # 驱动配置信息
    name: mydb
    druid:
      stat-view-servlet:
        enabled: true
        url: /druid
        login-username: admin
        login-password: admin
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://172.16.98.142:3306/ydh
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        validationQuery: select '1'
        initialSize: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
#        filters: stat,wall
        filters: stat,wall,log4j
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      slave:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://172.16.98.142:3306/ydh2
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        validationQuery: select '1'
        initialSize: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
#        filters: stat,wall
        filters: stat,wall,log4j
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://172.16.131.32:3306/ydh
#    username: root
#    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource
#    #连接池的配置信息
#    validationQuery: select 'x'
#    initialSize: 5
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxPoolPreparedStatementPerConnectionSize: 20
#    filters: stat,wall,log4j
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
mybatis:
  configuration:
    map-underscore-to-camel-case=true: true # 返回结果驼峰
  mapper-locations: mapper/*.xml            # xml文件
  type-aliases-package: com.ydh.redsheep.database.pojo # 转名字
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.ydh.redsheep.database.pojo
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto    # 主键自增策略
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#      table-prefix: "" # 前缀

#日志
logging:
  config: classpath:log4j2.xml