#服务参数配置
server:
  port: 80
  servlet:
    context-path: /
spring:
  data:
    redis:
      repositories:
        enabled: true
  redis:
    host: r-bp1594add6596dd4pd.redis.rds.aliyuncs.com
    port: 6379
    password: '!Yiwise0915='
    database: 0
    # 连接超时时间（毫秒）
    timeout:
    # 连接池
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最小空闲连接
        min-idle: 1
    # 主从复制和哨兵模式
#    sentinel:
#      master: mymaster
#      nodes: 192.168.2.188:26379,192.168.2.188:26380,192.168.2.188:26381
  session:
    store-type: redis
