#服务参数配置
server:
  port: 80
  servlet:
    context-path: /

dest:
  destA: mydest

spring:
  rabbitmq:
    host: 172.16.131.16
    username: root
    password: 123456
    port: 5672
    virtual-host: /
#    listener:
#      type: simple
#      simple:
#        max-concurrency: 10
#        concurrency: 5
#        prefetch: 10
#        acknowledge-mode: manual
