#############系统配置##################################
spring:
  application:
    name: base
  profiles:
    active: dev #设置配置文件
  datasource:
    # 驱动配置信息
    name: mydb
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.131.21:3306/ydh
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    #连接池的配置信息
    validationQuery: select 'x'
    initialSize: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#mybatis:
#  configuration:
#    map-underscore-to-camel-case=true: true # 返回结果驼峰
#  mapper-locations: mapper/*.xml            # xml文件
#  type-aliases-package: com.ydh.redsheep.base.pojo # 转名字
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.ydh.redsheep.base.pojo
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto    # 主键自增策略
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#      table-prefix: "" # 前缀


#日志
logging:
  # logback.xml的加载早于application.properties，所以如果在logback.xml中使用了变量，而恰好这个变量是写在application.properties时，
  # 那么就会获取不到，只要改成logback-spring.xml就可以解决。
  config: classpath:log4j2.xml

#############自定义配置##################################
#自定义参数配置
person:
  height: 171cm
  weight: 62kg
  name: ydh
  content: "height: ${person.height}; weight: ${person.weight}; name: ${person.name}"
  hobby: [ 吃饭,睡觉,打豆豆 ]
  family: [ father,mother ]
  map: { k1: v1,k2: v2 }
  pet: { type: dog,name: 旺财 }